# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.6.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images

    working_directory: ~/repo

    environment: 
      DEBUG: false
      TEST: true
      DJANGO_SETTINGS_MODULE: mainsite.settings

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install library
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python setup.py install      
            pip install pytest pylint mypy

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          context: global
          command: |
            . venv/bin/activate
            pylint -E bitcart
            mypy bitcart
            pytest --cov=.

      - store_artifacts:
          path: test-reports
          destination: test-reports
          
